apiVersion: v1
kind: Service
metadata:
  name: smt-service
spec:
  type: NodePort
  ports:
  - targetPort: 8001
    port: 8001
    nodePort: 30008
  selector:
    app: smt-website
    type: front-end
