apiVersion: v1
kind: ReplicationController
metadata:
  name: repication
  labels:
    app: front-end
    type: repica
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: summa
        type: web-server
    spec:
      containers:
       - name: nginx
         image: nginx
  replicas: 2
