apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels: 
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:  
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
       - name: nginx
         image: nginx
